// Public surface for charts: legacy `c:` (chart.ts), `cx:` chartex
// (cx/chartex.ts), and user-shape overlays (user-shapes.ts).

export type {
  Area3DChart,
  AreaChart,
  Bar3DChart,
  BarChart,
  BarDirection,
  BarFrame,
  BarSeries,
  BubbleChart,
  BubbleSeries,
  BubbleSizeRepresents,
  AxisCrossBetween,
  AxisCrosses,
  AxisOrientation,
  AxisScaling,
  CategoryAxis,
  CategoryLabelAlignment,
  CategoryRef,
  ChartKind,
  ChartNumberFormat,
  ChartSpace,
  ChartTitle,
  DateAxis,
  DataLabel,
  DataLabelList,
  DataLabelPosition,
  DataPoint,
  DoughnutChart,
  ErrorBarDirection,
  ErrorBars,
  ErrorBarType,
  ErrorValType,
  Gridlines,
  GroupingType,
  HiLowLines,
  Layout,
  LayoutMode,
  LayoutTarget,
  Legend,
  LegendPosition,
  Line3DChart,
  LineChart,
  LineSeries,
  ManualLayout,
  Marker,
  MarkerSymbol,
  NumericRef,
  OfPieChart,
  OfPieType,
  Pie3DChart,
  PieChart,
  PlotArea,
  RadarChart,
  RadarStyle,
  ScatterChart,
  ScatterSeries,
  ScatterStyle,
  SeriesAxis,
  SplitType,
  StockChart,
  Surface3DChart,
  SurfaceChart,
  SurfaceFrame,
  TickLabelPosition,
  TickMark,
  TimeUnit,
  Trendline,
  TrendlineType,
  UpDownBars,
  ValueAxis,
  View3D,
} from './chart.js';
export {
  makeArea3DChart,
  makeAreaChart,
  makeBar3DChart,
  makeBarChart,
  makeBarSeries,
  makeBubbleChart,
  makeBubbleSeries,
  makeChartSpace,
  makeDoughnutChart,
  makeLine3DChart,
  makeLineChart,
  makeOfPieChart,
  makePie3DChart,
  makePieChart,
  makeRadarChart,
  makeScatterChart,
  makeScatterSeries,
  makeStockChart,
  makeSurface3DChart,
  makeSurfaceChart,
} from './chart.js';
export type {
  CxAxis,
  CxChart,
  CxChartData,
  CxChartSpace,
  CxData,
  CxDataLabelPos,
  CxDataLabels,
  CxDim,
  CxExternalData,
  CxLayoutId,
  CxLayoutPr,
  CxLegend,
  CxNumDim,
  CxPlotArea,
  CxPoint,
  CxSeries,
  CxStrDim,
  CxTitle,
} from './cx/chartex.js';
export {
  makeBoxWhiskerChart,
  makeCxAxis,
  makeCxChartSpace,
  makeCxData,
  makeCxNumDim,
  makeCxSeries,
  makeCxStrDim,
  makeFunnelChart,
  makeHistogramChart,
  makeParetoChart,
  makeRegionMapChart,
  makeSunburstChart,
  makeTreemapChart,
  makeWaterfallChart,
} from './cx/chartex.js';
export type {
  ChartDrawing,
  ChartDrawingPicture,
  ChartDrawingShape,
  ChartRelativeMarker,
  UserShapeAnchor,
  UserShapeContent,
} from './user-shapes.js';
export {
  makeAbsSizeAnchor,
  makeChartDrawing,
  makeChartShape,
  makeRelSizeAnchor,
} from './user-shapes.js';
