// Phase 1 §3 XML layer entrypoint. Parser / serializer / iterparse land
// in subsequent /loop turns; this turn ships the namespace catalog and
// the lightweight XmlNode representation.

export type { SaxEvent, SaxInput } from './iterparse.js';
export { iterParse } from './iterparse.js';
export {
  ACTIVEX_TYPE,
  // namespace constants — re-exported for ergonomics
  ARC_APP,
  ARC_CONTENT_TYPES,
  ARC_CORE,
  ARC_CUSTOM,
  ARC_CUSTOM_UI,
  ARC_ROOT_RELS,
  ARC_SHARED_STRINGS,
  ARC_STYLE,
  ARC_THEME,
  ARC_WORKBOOK,
  ARC_WORKBOOK_RELS,
  C14_NS,
  C15_NS,
  C16_NS,
  CHART_DRAWING_NS,
  CHART_NS,
  CHART_TYPE,
  CHARTSHAPE_TYPE,
  CHARTSHEET_TYPE,
  COMMENTS_NS,
  COMMENTS_TYPE,
  CONTYPES_NS,
  COREPROPS_NS,
  CPROPS_FMTID,
  CPROPS_TYPE,
  CTRLPROPS_TYPE,
  CUSTOMUI_NS,
  CUSTPROPS_NS,
  CX_NS,
  DCMITYPE_NS,
  DCORE_NS,
  DCTERMS_NS,
  DCTERMS_PREFIX,
  DEFAULT_PREFIXES,
  DRAWING_NS,
  DRAWING_TYPE,
  EXTERNAL_LINK_NS,
  EXTERNAL_LINK_TYPE,
  IMAGE_NS,
  MARKUP_COMPAT_NS,
  PACKAGE_CHARTS,
  PACKAGE_CHARTSHEETS,
  PACKAGE_CHARTSHEETS_RELS,
  PACKAGE_DRAWINGS,
  PACKAGE_IMAGES,
  PACKAGE_PIVOT_CACHE,
  PACKAGE_PIVOT_TABLE,
  PACKAGE_PROPS,
  PACKAGE_RELS,
  PACKAGE_THEME,
  PACKAGE_WORKSHEET_RELS,
  PACKAGE_WORKSHEETS,
  PACKAGE_XL,
  PICTURE_NS,
  PKG_REL_NS,
  parseQName,
  qname,
  REL_NS,
  SHARED_STRINGS_TYPE,
  SHEET_DRAWING_NS,
  SHEET_MAIN_NS,
  STYLES_TYPE,
  THEME_TYPE,
  THREADED_COMMENTS_NS,
  VBA_TYPE,
  VML_NS,
  VTYPES_NS,
  WORKSHEET_TYPE,
  X14_NS,
  X15_NS,
  X16_NS,
  XLSM_TYPE,
  XLSX_TYPE,
  XLTM_TYPE,
  XLTX_TYPE,
  XML_NS,
  XPROPS_NS,
  XSI_NS,
} from './namespaces.js';
export { parseXml } from './parser.js';
export type { SerializeOptions } from './serializer.js';
export { serializeXml } from './serializer.js';
export type { XmlStreamWriter, XmlStreamWriterOptions } from './stream-writer.js';
export { createXmlStreamWriter } from './stream-writer.js';
export type { XmlNode } from './tree.js';
export { appendChild, el, elNs, findChild, findChildren } from './tree.js';
